title: In Motion Photography
email: rob@inmotionfl.com
description: >-  I am a passionate photographer whose journey began in 2020. With a love for adventure and the great outdoors,
 I capture the raw beauty of the world through my lens, often while climbing mountains and exploring remote landscapes.
 My work is driven by a desire to immortalize fleeting moments, showcase the power of nature, and inspire others to connect
 with the world around them. Through each shot, I aim to blend artistry with exploration, creating images that evoke wonder 
 and a sense of discovery.
baseurl: "" # the subpath of your site, e.g. /blog
url: "inmotionfl.com" 
author: Rob Neal

instagram: #inmotionphotog
pinterest: #
facebook: #
twitter: #

plugins:
  - jekyll-feed
sass:
  sass_dir: scss
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md


